arch:
  - amd64
  - ppc64le
language: c
sudo: true
compiler:
  - clang
dist: xenial
addons:
  apt:
    packages:
      - gcc-5-aarch64-linux-gnu
      - g++-5-aarch64-linux-gnu
      - gcc-5-arm-linux-gnueabihf
      - g++-5-arm-linux-gnueabihf
      - gcc-5-multilib
      - g++-5-multilib
      - qemu-user-static
      - binfmt-support

branches:
  only:
    - master

matrix:
  include: # ordered by execution time, slowest first
    - env: CONF=armhf
    - env: CONF=aarch64
    - env: CONF=debug
    - env: CONF=debugnox64
    - env: CONF=release
    - env: CONF=releasenox64
    - env: CONF=amalgamation
    # power jobs added.
    - env: CONF=armhf
      arch: ppc64le
    - env: CONF=aarch64
      arch: ppc64le    
    - env: CONF=debug
      arch: ppc64le      
    - env: CONF=debugnox64
      arch: ppc64le    
    - env: CONF=release
      arch: ppc64le
    - env: CONF=releasenox64
      arch: ppc64le
    - env: CONF=amalgamation
      arch: ppc64le
    script: tools/travis.sh $CONF

