CRoaring: roaring::Roaring64Map Class Reference
roaring::Roaring64Map Class Reference
#include <roaring64map.hh>
Public Types
typedef Roaring64MapSetBitForwardIterator const_iterator
typedef Roaring64MapSetBitBiDirectionalIterator const_bidirectional_iterator
Public Member Functions
Roaring64Map ()=default
Roaring64Map (size_t n, const uint32_t *data)
Roaring64Map (size_t n, const uint64_t *data)
Roaring64Map (std::initializer_list< uint64_t > l)
Roaring64Map (const Roaring &r)
Roaring64Map (Roaring &&r)
Roaring64Map (roaring_bitmap_t *s)
Roaring64Map (const Roaring64Map &r)=default
Roaring64Map (Roaring64Map &&r) noexcept=default
Roaring64Map & operator= (const Roaring64Map &r)=default
Roaring64Map & operator= (Roaring64Map &&r) noexcept=default
Roaring64Map & operator= (std::initializer_list< uint64_t > l)
void add (uint32_t x)
void add (uint64_t x)
bool addChecked (uint32_t x)
bool addChecked (uint64_t x)
void addRange (uint64_t min, uint64_t max)
void addRangeClosed (uint32_t min, uint32_t max)
void addRangeClosed (uint64_t min, uint64_t max)
void addMany (size_t n_args, const uint32_t *vals)
void addMany (size_t n_args, const uint64_t *vals)
void remove (uint32_t x)
void remove (uint64_t x)
bool removeChecked (uint32_t x)
bool removeChecked (uint64_t x)
void removeRange (uint64_t min, uint64_t max)
void removeRangeClosed (uint32_t min, uint32_t max)
void removeRangeClosed (uint64_t min, uint64_t max)
void clear ()
uint64_t maximum () const
uint64_t minimum () const
bool contains (uint32_t x) const
bool contains (uint64_t x) const
Roaring64Map & operator&= (const Roaring64Map &other)
Roaring64Map & operator-= (const Roaring64Map &other)
Roaring64Map & operator|= (const Roaring64Map &other)
Roaring64Map & operator^= (const Roaring64Map &other)
void swap (Roaring64Map &r)
uint64_t cardinality () const
bool isEmpty () const
bool isFull () const
bool isSubset (const Roaring64Map &r) const
bool isStrictSubset (const Roaring64Map &r) const
void toUint64Array (uint64_t *ans) const
bool operator== (const Roaring64Map &r) const
void flip (uint64_t min, uint64_t max)
void flipClosed (uint32_t min, uint32_t max)
void flipClosed (uint64_t min, uint64_t max)
bool removeRunCompression ()
bool runOptimize ()
size_t shrinkToFit ()
void iterate (api::roaring_iterator64 iterator, void *ptr) const
bool select (uint64_t rank, uint64_t *element) const
uint64_t rank (uint64_t x) const
size_t write (char *buf, bool portable=true) const
size_t getSizeInBytes (bool portable=true) const
void writeFrozen (char *buf) const
size_t getFrozenSizeInBytes () const
Roaring64Map operator& (const Roaring64Map &o) const
Roaring64Map operator- (const Roaring64Map &o) const
Roaring64Map operator| (const Roaring64Map &o) const
Roaring64Map operator^ (const Roaring64Map &o) const
void setCopyOnWrite (bool val)
void printf () const
std::string toString () const
bool getCopyOnWrite () const
const_iterator begin () const
const_iterator end () const
Static Public Member Functions
static Roaring64Map bitmapOf (size_t n...)
static Roaring64Map bitmapOfList (std::initializer_list< uint64_t > l)
static Roaring64Map read (const char *buf, bool portable=true)
static Roaring64Map readSafe (const char *buf, size_t maxbytes)
static const Roaring64Map frozenView (const char *buf)
static Roaring64Map fastunion (size_t n, const Roaring64Map **inputs)
Friends
class Roaring64MapSetBitForwardIterator
class Roaring64MapSetBitBiDirectionalIterator
Detailed Description
Definition at line 37 of file roaring64map.hh.
Member Typedef Documentation
const_bidirectional_iterator
typedef Roaring64MapSetBitBiDirectionalIterator roaring::Roaring64Map::const_bidirectional_iterator
Definition at line 1513 of file roaring64map.hh.
const_iterator
typedef Roaring64MapSetBitForwardIterator roaring::Roaring64Map::const_iterator
Definition at line 1512 of file roaring64map.hh.
Constructor & Destructor Documentation
Roaring64Map() [1/9]
roaring::Roaring64Map::Roaring64Map () default
Create an empty bitmap
Referenced by operator&(), operator-(), operator=(), operator^(), and operator|().
Roaring64Map() [2/9]
roaring::Roaring64Map::Roaring64Map (size_t n, const uint32_t * data) inline
Construct a bitmap from a list of 32-bit integer values.
Definition at line 49 of file roaring64map.hh.
References addMany().
Roaring64Map() [3/9]
roaring::Roaring64Map::Roaring64Map (size_t n, const uint64_t * data) inline
Construct a bitmap from a list of 64-bit integer values.
Definition at line 54 of file roaring64map.hh.
References addMany().
Roaring64Map() [4/9]
roaring::Roaring64Map::Roaring64Map (std::initializer_list< uint64_t > l) inline
Construct a bitmap from an initializer list.
Definition at line 59 of file roaring64map.hh.
References addMany().
Roaring64Map() [5/9]
roaring::Roaring64Map::Roaring64Map (const Roaring & r) inline explicit
Construct a 64-bit map from a 32-bit one
Definition at line 66 of file roaring64map.hh.
Roaring64Map() [6/9]
roaring::Roaring64Map::Roaring64Map (Roaring && r) inline explicit
Construct a 64-bit map from a 32-bit rvalue
Definition at line 71 of file roaring64map.hh.
Roaring64Map() [7/9]
roaring::Roaring64Map::Roaring64Map (roaring_bitmap_t * s) inline explicit
Construct a roaring object from the C struct.
Passing a NULL point is unsafe.
Definition at line 78 of file roaring64map.hh.
Roaring64Map() [8/9]
roaring::Roaring64Map::Roaring64Map (const Roaring64Map & r) default
Roaring64Map() [9/9]
roaring::Roaring64Map::Roaring64Map (Roaring64Map && r) default noexcept
Member Function Documentation
add() [1/2]
void roaring::Roaring64Map::add (uint32_t x) inline
Adds value x.
Definition at line 132 of file roaring64map.hh.
References roaring::Roaring::add().
Referenced by bitmapOf().
add() [2/2]
void roaring::Roaring64Map::add (uint64_t x) inline
Adds value x.
Definition at line 139 of file roaring64map.hh.
References roaring::Roaring::add().
addChecked() [1/2]
bool roaring::Roaring64Map::addChecked (uint32_t x) inline
Adds value x. Returns true if a new value was added, false if the value was already present.
Definition at line 148 of file roaring64map.hh.
References roaring::Roaring::addChecked().
addChecked() [2/2]
bool roaring::Roaring64Map::addChecked (uint64_t x) inline
Adds value x. Returns true if a new value was added, false if the value was already present.
Definition at line 157 of file roaring64map.hh.
References roaring::Roaring::addChecked().
addMany() [1/2]
void roaring::Roaring64Map::addMany (size_t n_args, const uint32_t * vals) inline
Adds 'n_args' values from the contiguous memory range starting at 'vals'.
Definition at line 245 of file roaring64map.hh.
References roaring::Roaring::addMany().
Referenced by bitmapOfList(), and Roaring64Map().
addMany() [2/2]
void roaring::Roaring64Map::addMany (size_t n_args, const uint64_t * vals) inline
Adds 'n_args' values from the contiguous memory range starting at 'vals'.
Definition at line 252 of file roaring64map.hh.
References roaring::Roaring::add().
addRange()
void roaring::Roaring64Map::addRange (uint64_t min, uint64_t max) inline
Adds all values in the half-open interval [min, max).
Definition at line 164 of file roaring64map.hh.
References addRangeClosed().
addRangeClosed() [1/2]
void roaring::Roaring64Map::addRangeClosed (uint32_t min, uint32_t max) inline
Adds all values in the closed interval [min, max].
Definition at line 174 of file roaring64map.hh.
References roaring::Roaring::addRangeClosed().
Referenced by addRange().
addRangeClosed() [2/2]
void roaring::Roaring64Map::addRangeClosed (uint64_t min, uint64_t max) inline
Adds all values in the closed interval [min, max]
Definition at line 181 of file roaring64map.hh.
begin()
Roaring64MapSetBitForwardIterator roaring::Roaring64Map::begin () const inline
Returns an iterator that can be used to access the position of the set bits. The running time complexity of a full scan is proportional to the number of set bits: be aware that if you have long strings of 1s, this can be very inefficient.
It can be much faster to use the toArray method if you want to retrieve the set bits.
Definition at line 1835 of file roaring64map.hh.
References Roaring64MapSetBitForwardIterator.
bitmapOf()
static Roaring64Map roaring::Roaring64Map::bitmapOf (size_t n...) inline static
Construct a bitmap from a list of uint64_t values.
Definition at line 108 of file roaring64map.hh.
References add().
bitmapOfList()
static Roaring64Map roaring::Roaring64Map::bitmapOfList (std::initializer_list< uint64_t > l) inline static
Construct a bitmap from a list of uint64_t values. E.g., bitmapOfList({1,2,3}).
Definition at line 123 of file roaring64map.hh.
References addMany().
cardinality()
uint64_t roaring::Roaring64Map::cardinality () const inline
Get the cardinality of the bitmap (number of elements). Throws std::length_error in the special case where the bitmap is full (cardinality() == 2^64). Check isFull() before calling to avoid exception.
Definition at line 742 of file roaring64map.hh.
References isFull(), and ROARING_TERMINATE.
Referenced by isStrictSubset().
clear()
void roaring::Roaring64Map::clear () inline
Clears the bitmap.
Definition at line 443 of file roaring64map.hh.
Referenced by fastunion().
contains() [1/2]
bool roaring::Roaring64Map::contains (uint32_t x) const inline
Check if value x is present
Definition at line 482 of file roaring64map.hh.
contains() [2/2]
bool roaring::Roaring64Map::contains (uint64_t x) const inline
Definition at line 485 of file roaring64map.hh.
end()
Roaring64MapSetBitForwardIterator roaring::Roaring64Map::end () const inline
A bogus iterator that can be used together with begin() for constructions such as: for (auto i = b.begin(); * i!=b.end(); ++i) {}
Definition at line 1839 of file roaring64map.hh.
References Roaring64MapSetBitForwardIterator.
Referenced by fastunion().
fastunion()
static Roaring64Map roaring::Roaring64Map::fastunion (size_t n, const Roaring64Map ** inputs) inline static
Computes the logical or (union) between "n" bitmaps (referenced by a pointer).
Definition at line 1389 of file roaring64map.hh.
References clear(), and end().
flip()
void roaring::Roaring64Map::flip (uint64_t min, uint64_t max) inline
Computes the negation of the roaring bitmap within the half-open interval [min, max). Areas outside the interval are unchanged.
Definition at line 886 of file roaring64map.hh.
References flipClosed().
flipClosed() [1/2]
void roaring::Roaring64Map::flipClosed (uint32_t min, uint32_t max) inline
Computes the negation of the roaring bitmap within the closed interval [min, max]. Areas outside the interval are unchanged.
Definition at line 897 of file roaring64map.hh.
Referenced by flip().
flipClosed() [2/2]
void roaring::Roaring64Map::flipClosed (uint64_t min, uint64_t max) inline
Computes the negation of the roaring bitmap within the closed interval [min, max]. Areas outside the interval are unchanged.
Definition at line 918 of file roaring64map.hh.
frozenView()
static const Roaring64Map roaring::Roaring64Map::frozenView (const char * buf) inline static
Definition at line 1215 of file roaring64map.hh.
References roaring::Roaring::frozenView(), and read().
getCopyOnWrite()
bool roaring::Roaring64Map::getCopyOnWrite () const inline
Whether or not copy and write is active.
Definition at line 1383 of file roaring64map.hh.
getFrozenSizeInBytes()
size_t roaring::Roaring64Map::getFrozenSizeInBytes () const inline
Definition at line 1288 of file roaring64map.hh.
getSizeInBytes()
size_t roaring::Roaring64Map::getSizeInBytes (bool portable = true) const inline
Return the number of bytes required to serialize this bitmap (meant to be compatible with Java and Go versions)
Setting the portable flag to false enable a custom format that can save space compared to the portable format (e.g., for very sparse bitmaps).
Definition at line 1202 of file roaring64map.hh.
isEmpty()
bool roaring::Roaring64Map::isEmpty () const inline
Returns true if the bitmap is empty (cardinality is zero).
Definition at line 763 of file roaring64map.hh.
isFull()
bool roaring::Roaring64Map::isFull () const inline
Returns true if the bitmap is full (cardinality is max uint64_t + 1).
Definition at line 773 of file roaring64map.hh.
Referenced by cardinality().
isStrictSubset()
bool roaring::Roaring64Map::isStrictSubset (const Roaring64Map & r) const inline
Returns true if the bitmap is strict subset of the other. Throws std::length_error in the special case where the bitmap is full (cardinality() == 2^64). Check isFull() before calling to avoid exception.
Definition at line 815 of file roaring64map.hh.
References cardinality(), and isSubset().
isSubset()
bool roaring::Roaring64Map::isSubset (const Roaring64Map & r) const inline
Returns true if the bitmap is subset of the other.
Definition at line 796 of file roaring64map.hh.
Referenced by isStrictSubset().
iterate()
void roaring::Roaring64Map::iterate (api::roaring_iterator64 iterator, void * ptr) const inline
Iterate over the bitmap elements in order(start from the smallest one) and call iterator once for every element until the iterator function returns false. To iterate over all values, the iterator function should always return true.
The roaring_iterator64 parameter is a pointer to a function that returns bool (true means that the iteration should continue while false means that it should stop), and takes (uint64_t element, void* ptr) as inputs.
Definition at line 1034 of file roaring64map.hh.
maximum()
uint64_t roaring::Roaring64Map::maximum () const inline
Return the largest value (if not empty)
Definition at line 450 of file roaring64map.hh.
minimum()
uint64_t roaring::Roaring64Map::minimum () const inline
Return the smallest value (if not empty)
Definition at line 466 of file roaring64map.hh.
operator&()
Roaring64Map roaring::Roaring64Map::operator& (const Roaring64Map & o) const inline
Computes the intersection between two bitmaps and returns new bitmap. The current bitmap and the provided bitmap are unchanged.
Performance hint: if you are computing the intersection between several bitmaps, two-by-two, it is best to start with the smallest bitmap. Consider also using the operator &= to avoid needlessly creating many temporary bitmaps.
Definition at line 1316 of file roaring64map.hh.
References Roaring64Map().
operator&=()
Roaring64Map& roaring::Roaring64Map::operator&= (const Roaring64Map & other) inline
Compute the intersection of the current bitmap and the provided bitmap, writing the result in the current bitmap. The provided bitmap is not modified.
Performance hint: if you are computing the intersection between several bitmaps, two-by-two, it is best to start with the smallest bitmap.
Definition at line 499 of file roaring64map.hh.
operator-()
Roaring64Map roaring::Roaring64Map::operator- (const Roaring64Map & o) const inline
Computes the difference between two bitmaps and returns new bitmap. The current bitmap and the provided bitmap are unchanged.
Definition at line 1324 of file roaring64map.hh.
References Roaring64Map().
operator-=()
Roaring64Map& roaring::Roaring64Map::operator-= (const Roaring64Map & other) inline
Compute the difference between the current bitmap and the provided bitmap, writing the result in the current bitmap. The provided bitmap is not modified.
Definition at line 556 of file roaring64map.hh.
operator=() [1/3]
Roaring64Map& roaring::Roaring64Map::operator= (const Roaring64Map & r) default
Copy assignment operator.
operator=() [2/3]
Roaring64Map& roaring::Roaring64Map::operator= (Roaring64Map && r) default noexcept
Move assignment operator.
operator=() [3/3]
Roaring64Map& roaring::Roaring64Map::operator= (std::initializer_list< uint64_t > l) inline
Assignment from an initializer list.
Definition at line 99 of file roaring64map.hh.
References Roaring64Map().
operator==()
bool roaring::Roaring64Map::operator== (const Roaring64Map & r) const inline
Return true if the two bitmaps contain the same elements.
Definition at line 840 of file roaring64map.hh.
operator^()
Roaring64Map roaring::Roaring64Map::operator^ (const Roaring64Map & o) const inline
Computes the symmetric union between two bitmaps and returns new bitmap. The current bitmap and the provided bitmap are unchanged.
Definition at line 1340 of file roaring64map.hh.
References Roaring64Map().
operator^=()
Roaring64Map& roaring::Roaring64Map::operator^= (const Roaring64Map & other) inline
Compute the XOR of the current bitmap and the provided bitmap, writing the result in the current bitmap. The provided bitmap is not modified.
Definition at line 676 of file roaring64map.hh.
operator|()
Roaring64Map roaring::Roaring64Map::operator| (const Roaring64Map & o) const inline
Computes the union between two bitmaps and returns new bitmap. The current bitmap and the provided bitmap are unchanged.
Definition at line 1332 of file roaring64map.hh.
References Roaring64Map().
operator|=()
Roaring64Map& roaring::Roaring64Map::operator|= (const Roaring64Map & other) inline
Compute the union of the current bitmap and the provided bitmap, writing the result in the current bitmap. The provided bitmap is not modified.
See also the fastunion function to aggregate many bitmaps more quickly.
Definition at line 624 of file roaring64map.hh.
printf()
void roaring::Roaring64Map::printf () const inline
Print the contents of the bitmap to stdout. Note: this method adds a final newline, but toString() does not.
Definition at line 1360 of file roaring64map.hh.
rank()
uint64_t roaring::Roaring64Map::rank (uint64_t x) const inline
Returns the number of integers that are smaller or equal to x.
Definition at line 1076 of file roaring64map.hh.
Referenced by select().
read()
static Roaring64Map roaring::Roaring64Map::read (const char * buf, bool portable = true) inline static
Read a bitmap from a serialized version. This is meant to be compatible with the Java and Go versions.
Setting the portable flag to false enable a custom format that can save space compared to the portable format (e.g., for very sparse bitmaps).
This function is unsafe in the sense that if you provide bad data, many bytes could be read, possibly causing a buffer overflow. See also readSafe.
Definition at line 1136 of file roaring64map.hh.
References roaring::Roaring::getSizeInBytes(), and roaring::Roaring::read().
Referenced by frozenView().
readSafe()
static Roaring64Map roaring::Roaring64Map::readSafe (const char * buf, size_t maxbytes) inline static
Read a bitmap from a serialized version, reading no more than maxbytes bytes. This is meant to be compatible with the Java and Go versions.
Setting the portable flag to false enable a custom format that can save space compared to the portable format (e.g., for very sparse bitmaps).
Definition at line 1165 of file roaring64map.hh.
References roaring::Roaring::getSizeInBytes(), roaring::Roaring::readSafe(), and ROARING_TERMINATE.
remove() [1/2]
void roaring::Roaring64Map::remove (uint32_t x) inline
Removes value x.
Definition at line 272 of file roaring64map.hh.
remove() [2/2]
void roaring::Roaring64Map::remove (uint64_t x) inline
Removes value x.
Definition at line 287 of file roaring64map.hh.
removeChecked() [1/2]
bool roaring::Roaring64Map::removeChecked (uint32_t x) inline
Removes value x Returns true if a new value was removed, false if the value was not present.
Definition at line 302 of file roaring64map.hh.
removeChecked() [2/2]
bool roaring::Roaring64Map::removeChecked (uint64_t x) inline
Remove value x Returns true if a new value was removed, false if the value was not present.
Definition at line 322 of file roaring64map.hh.
removeRange()
void roaring::Roaring64Map::removeRange (uint64_t min, uint64_t max) inline
Removes all values in the half-open interval [min, max).
Definition at line 338 of file roaring64map.hh.
References removeRangeClosed().
removeRangeClosed() [1/2]
void roaring::Roaring64Map::removeRangeClosed (uint32_t min, uint32_t max) inline
Removes all values in the closed interval [min, max].
Definition at line 348 of file roaring64map.hh.
Referenced by removeRange().
removeRangeClosed() [2/2]
void roaring::Roaring64Map::removeRangeClosed (uint64_t min, uint64_t max) inline
Removes all values in the closed interval [min, max].
Definition at line 364 of file roaring64map.hh.
removeRunCompression()
bool roaring::Roaring64Map::removeRunCompression () inline
Remove run-length encoding even when it is more space efficient return whether a change was applied
Definition at line 981 of file roaring64map.hh.
runOptimize()
bool roaring::Roaring64Map::runOptimize () inline
Convert array and bitmap containers to run containers when it is more efficient; also convert from run containers when more space efficient. Returns true if the result has at least one run container. Additional savings might be possible by calling shrinkToFit().
Definition at line 995 of file roaring64map.hh.
select()
bool roaring::Roaring64Map::select (uint64_t rank, uint64_t * element) const inline
Selects the value at index 'rank' in the bitmap, where the smallest value is at index 0. If 'rank' < cardinality(), returns true with *element set to the element of the specified rank. Otherwise, returns false and the contents of *element are unspecified.
Definition at line 1051 of file roaring64map.hh.
References rank(), and ROARING_TERMINATE.
setCopyOnWrite()
void roaring::Roaring64Map::setCopyOnWrite (bool val) inline
Whether or not we apply copy and write.
Definition at line 1347 of file roaring64map.hh.
shrinkToFit()
size_t roaring::Roaring64Map::shrinkToFit () inline
If needed, reallocate memory to shrink the memory usage. Returns the number of bytes saved.
Definition at line 1007 of file roaring64map.hh.
swap()
void roaring::Roaring64Map::swap (Roaring64Map & r) inline
Exchange the content of this bitmap with another.
Definition at line 734 of file roaring64map.hh.
toString()
std::string roaring::Roaring64Map::toString () const inline
Print the contents of the bitmap into a string.
Definition at line 1371 of file roaring64map.hh.
toUint64Array()
void roaring::Roaring64Map::toUint64Array (uint64_t * ans) const inline
Convert the bitmap to an array. Write the output to "ans", caller is responsible to ensure that there is enough memory allocated (e.g., ans = new uint32[mybitmap.cardinality()];)
Definition at line 825 of file roaring64map.hh.
write()
size_t roaring::Roaring64Map::write (char * buf, bool portable = true) const inline
Write a bitmap to a char buffer. This is meant to be compatible with the Java and Go versions. Returns how many bytes were written which should be getSizeInBytes().
Setting the portable flag to false enables a custom format that can save space compared to the portable format (e.g., for very sparse bitmaps).
Definition at line 1104 of file roaring64map.hh.
writeFrozen()
void roaring::Roaring64Map::writeFrozen (char * buf) const inline
Definition at line 1259 of file roaring64map.hh.
Friends And Related Function Documentation
Roaring64MapSetBitBiDirectionalIterator
friend class Roaring64MapSetBitBiDirectionalIterator friend
Definition at line 1511 of file roaring64map.hh.
Roaring64MapSetBitForwardIterator
friend class Roaring64MapSetBitForwardIterator friend
Definition at line 1510 of file roaring64map.hh.
Referenced by begin(), and end().
The documentation for this class was generated from the following file:
cpp/roaring64map.hh