CRoaring: roaring::Roaring64MapSetBitBiDirectionalIterator Class Reference
roaring::Roaring64MapSetBitBiDirectionalIterator Class Reference
#include <roaring64map.hh>
Public Types
typedef std::bidirectional_iterator_tag iterator_category
typedef uint64_t * pointer
typedef uint64_t & reference
typedef uint64_t value_type
typedef int64_t difference_type
typedef Roaring64MapSetBitBiDirectionalIterator type_of_iterator
Public Member Functions
Roaring64MapSetBitBiDirectionalIterator (const Roaring64Map &parent, bool exhausted=false)
value_type operator* () const
bool operator< (const type_of_iterator &o) const
bool operator<= (const type_of_iterator &o) const
bool operator> (const type_of_iterator &o) const
bool operator>= (const type_of_iterator &o) const
type_of_iterator & operator++ ()
type_of_iterator operator++ (int)
bool move_equalorlarger (const value_type &x)
CROARING_DEPRECATED bool move (const value_type &x)
type_of_iterator & operator-- ()
type_of_iterator operator-- (int)
bool operator== (const Roaring64MapSetBitBiDirectionalIterator &o) const
bool operator!= (const Roaring64MapSetBitBiDirectionalIterator &o) const
Detailed Description
Used to go through the set bits. Not optimally fast, but convenient.
Recommend to explicitly construct this iterator.
Definition at line 1723 of file roaring64map.hh.
Member Typedef Documentation
difference_type
typedef int64_t roaring::Roaring64MapSetBitBiDirectionalIterator::difference_type
Definition at line 1729 of file roaring64map.hh.
iterator_category
typedef std::bidirectional_iterator_tag roaring::Roaring64MapSetBitBiDirectionalIterator::iterator_category
Definition at line 1725 of file roaring64map.hh.
pointer
typedef uint64_t* roaring::Roaring64MapSetBitBiDirectionalIterator::pointer
Definition at line 1726 of file roaring64map.hh.
reference
typedef uint64_t& roaring::Roaring64MapSetBitBiDirectionalIterator::reference
Definition at line 1727 of file roaring64map.hh.
type_of_iterator
typedef Roaring64MapSetBitBiDirectionalIterator roaring::Roaring64MapSetBitBiDirectionalIterator::type_of_iterator
Definition at line 1730 of file roaring64map.hh.
value_type
typedef uint64_t roaring::Roaring64MapSetBitBiDirectionalIterator::value_type
Definition at line 1728 of file roaring64map.hh.
Constructor & Destructor Documentation
Roaring64MapSetBitBiDirectionalIterator()
roaring::Roaring64MapSetBitBiDirectionalIterator::Roaring64MapSetBitBiDirectionalIterator (const Roaring64Map & parent, bool exhausted = false) inline
Definition at line 1732 of file roaring64map.hh.
References roaring_iterator_init().
Member Function Documentation
move()
CROARING_DEPRECATED bool roaring::Roaring64MapSetBitBiDirectionalIterator::move (const value_type & x) inline
DEPRECATED, use move_equalorlarger.
Definition at line 1822 of file roaring64map.hh.
References move_equalorlarger().
move_equalorlarger()
bool roaring::Roaring64MapSetBitBiDirectionalIterator::move_equalorlarger (const value_type & x) inline
Move the iterator to the first value >= val. Return true if there is such a value.
Definition at line 1804 of file roaring64map.hh.
References roaring_iterator_init(), and roaring_uint32_iterator_move_equalorlarger().
Referenced by move().
operator!=()
bool roaring::Roaring64MapSetBitBiDirectionalIterator::operator!= (const Roaring64MapSetBitBiDirectionalIterator & o) const inline
Definition at line 1865 of file roaring64map.hh.
operator*()
value_type roaring::Roaring64MapSetBitBiDirectionalIterator::operator* () const inline
Provides the location of the set bit.
Definition at line 1751 of file roaring64map.hh.
operator++() [1/2]
type_of_iterator & roaring::Roaring64MapSetBitBiDirectionalIterator::operator++ () inline
Definition at line 1779 of file roaring64map.hh.
References roaring_iterator_init(), and roaring_uint32_iterator_advance().
operator++() [2/2]
type_of_iterator roaring::Roaring64MapSetBitBiDirectionalIterator::operator++ (int) inline
Definition at line 1789 of file roaring64map.hh.
References roaring_iterator_init(), and roaring_uint32_iterator_advance().
operator--() [1/2]
type_of_iterator & roaring::Roaring64MapSetBitBiDirectionalIterator::operator-- () inline
Definition at line 1826 of file roaring64map.hh.
References roaring_iterator_init_last(), and roaring_uint32_iterator_previous().
operator--() [2/2]
type_of_iterator roaring::Roaring64MapSetBitBiDirectionalIterator::operator-- (int) inline
Definition at line 1842 of file roaring64map.hh.
References roaring_iterator_init_last(), and roaring_uint32_iterator_previous().
operator<()
bool roaring::Roaring64MapSetBitBiDirectionalIterator::operator< (const type_of_iterator & o) const inline
Definition at line 1755 of file roaring64map.hh.
operator<=()
bool roaring::Roaring64MapSetBitBiDirectionalIterator::operator<= (const type_of_iterator & o) const inline
Definition at line 1761 of file roaring64map.hh.
operator==()
bool roaring::Roaring64MapSetBitBiDirectionalIterator::operator== (const Roaring64MapSetBitBiDirectionalIterator & o) const inline
Definition at line 1859 of file roaring64map.hh.
operator>()
bool roaring::Roaring64MapSetBitBiDirectionalIterator::operator> (const type_of_iterator & o) const inline
Definition at line 1767 of file roaring64map.hh.
operator>=()
bool roaring::Roaring64MapSetBitBiDirectionalIterator::operator>= (const type_of_iterator & o) const inline
Definition at line 1773 of file roaring64map.hh.
The documentation for this class was generated from the following file:
cpp/roaring64map.hh