name: Alpine Linux
'on':
  - push
  - pull_request
permissions:
  contents: read
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: start docker
        run: |
          docker run -w /src -dit --name alpine -v $PWD:/src alpine:latest
          echo 'docker exec alpine "$@";' > ./alpine.sh
          chmod +x ./alpine.sh
      - name: install packages
        run: |
          ./alpine.sh apk update
          ./alpine.sh apk add build-base cmake g++ linux-headers git bash
      - name: cmake
        run: |
          ./alpine.sh cmake -DENABLE_ROARING_TESTS=ON -B build_for_alpine
      - name: build
        run: |
          ./alpine.sh cmake --build build_for_alpine
      - name: test
        run: |
          ./alpine.sh bash -c "cd build_for_alpine && ctest"
      - name: cmakedebug
        run: |
          ./alpine.sh cmake -B build_for_alpine_debug -DCMAKE_BUILD_TYPE=Debug
      - name: builddebug
        run: |
          ./alpine.sh cmake --build build_for_alpine_debug
      - name: testdebug
        run: |
          ./alpine.sh bash -c "cd build_for_alpine_debug && ctest"
