name: Ubuntu-CI

'on':
  - push
  - pull_request


jobs:
  ci:
    name: ubuntu-gcc
    runs-on: ubuntu-latest

    env:
      CC: gcc
      CXX: g++

    steps: 
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_FLAGS=-fno-exceptions -DROARING_EXCEPTIONS=OFF ..
          cmake --build . 
          ctest . --output-on-failure
