name: Ubuntu-NoExceptions-CI

'on':
  - push
  - pull_request

permissions:
  contents: read

jobs:
  ci:
    name: ubuntu-gcc
    runs-on: ubuntu-latest

    env:
      CC: gcc
      CXX: g++

    steps: 
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_FLAGS=-fno-exceptions -DROARING_EXCEPTIONS=OFF -DENABLE_ROARING_TESTS=ON .. 
          cmake --build . 
          ctest . --output-on-failure
