name: Ubuntu-CI

'on':
  - push
  - pull_request

permissions:
  contents: read

jobs:
  ci:
    name: ubuntu-gcc
    runs-on: ubuntu-latest

    env:
      CC: gcc
      CXX: g++

    steps: 
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_FLAGS=-fno-exceptions -DROARING_EXCEPTIONS=OFF ..
          cmake --build . 
          ctest . --output-on-failure
