name: VS16-CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    name: windows-vs16
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - {gen: Visual Studio 16 2019, arch: Win32}
          - {gen: Visual Studio 16 2019, arch: x64}
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Configure
        run: |
          mkdir build
          cd build && cmake -G "${{matrix.gen}}" -A ${{matrix.arch}}  ..
      - name: Build
        run: cmake --build build --config Release
      - name: Run basic tests
        run: |
          cd build
          ctest -C Release --output-on-failure
      - name: Build Debug
        run: cmake --build build --config Debug
      - name: Run basic tests in Debug
        run: |
          cd build
          ctest -C Debug --output-on-failure