name: VS16-ARM-CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    name: windows-vs16
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - {gen: Visual Studio 16 2019, arch: ARM}
          - {gen: Visual Studio 16 2019, arch: ARM64}
    steps:
      - name: checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Configure
        run: |
          mkdir build
          cd build && cmake -G "${{matrix.gen}}" -A ${{matrix.arch}}  ..
      - name: Build
        run: cmake --build build --config Release
      - name: Build Debug
        run: cmake --build build --config Debug